modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
description = '''${mod_description}'''
logoFile = "${mod_logo_file}"
credits = '''${mod_credits}'''
authors = "${mod_authors}"
displayURL = "${mod_display_url}"
issueTrackerURL = "${mod_issue_tracker}"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

# Vampirism dependency
[[dependencies.${mod_id}]]
modId = "vampirism"
type = "required"
versionRange = "[${vampirism_version},)"
ordering = "AFTER"
side = "BOTH"

# Iron's Spells dependency
[[dependencies.${mod_id}]]
modId = "irons_spellbooks"
type = "required"
versionRange = "[${irons_spells_version},)"
ordering = "AFTER"
side = "BOTH"