modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mixins]]
config = "vampire_spells_addon.client.mixins.json"

[[mixins]]
config = "vampire_spells_addon.core.mixins.json"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
logoFile = "vampire_spells_addon.png"
description = '''${mod_description}'''
credits = '''${mod_credits}'''
authors = "${mod_authors}"
displayURL = "${mod_display_url}"
issueTrackerURL = "${mod_issue_tracker}"

[[dependencies.${mod_id}]]
modId = "${platform_loader_mod_id}"
type = "required"
versionRange = "${platform_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "vampirism"
type = "required"
versionRange = "${vampirism_version_range}"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "irons_spellbooks"
type = "required"
versionRange = "${irons_spells_version_range}"
ordering = "AFTER"
side = "BOTH"
